// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAWuwTpWDPsaq8U-cioTzzBamINkzywkk',
    appId: '1:318880748188:web:25f228fbb57a28533b1359',
    messagingSenderId: '318880748188',
    projectId: 'to-do-app-6c0d7',
    authDomain: 'to-do-app-6c0d7.firebaseapp.com',
    storageBucket: 'to-do-app-6c0d7.appspot.com',
    measurementId: 'G-M6BWJZ76ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWXFDK6h0UnV3rpzeFLfLNSGRlzmOopr0',
    appId: '1:318880748188:android:6e658291e71fc18a3b1359',
    messagingSenderId: '318880748188',
    projectId: 'to-do-app-6c0d7',
    storageBucket: 'to-do-app-6c0d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZc76A8F5jXPU2MmgFM8JGGs-ngWvP9Ns',
    appId: '1:318880748188:ios:b44ee3e00863c5133b1359',
    messagingSenderId: '318880748188',
    projectId: 'to-do-app-6c0d7',
    storageBucket: 'to-do-app-6c0d7.appspot.com',
    iosClientId: '318880748188-bh2gcqvh8anl7hlanokjnfdvilkvslgn.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZc76A8F5jXPU2MmgFM8JGGs-ngWvP9Ns',
    appId: '1:318880748188:ios:b44ee3e00863c5133b1359',
    messagingSenderId: '318880748188',
    projectId: 'to-do-app-6c0d7',
    storageBucket: 'to-do-app-6c0d7.appspot.com',
    iosClientId: '318880748188-bh2gcqvh8anl7hlanokjnfdvilkvslgn.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.todoApp',
  );
}
